### ISSUE TITLE
Add opengraph image to the repository

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remoting-opentelemetry-plugin#14]
During the GSoC timeframe we are likely to post the links to this repository A LOT. GitHub supports opengraph so that custom images can be added to Twitter/Facebook/etc. when posting the links. It would be great to have one for this projects. It could be something with Jenkins and OpenTelemetry, we have no special Remoting logo at the moment

In Jenkins we usually create opengraphs using Google Slides. You can find some examples in https://docs.google.com/presentation/d/1Q1PgNnRTgzBpVRXPqQo3PudzCa2eoc6_1_NRjFRMLrU/edit#slide=id.g8d21d9a9df_0_0 and below. You can reuse any of the slides

**Comment by Aki-7** [comment]
How about this?
Google sides link: https://docs.google.com/presentation/d/1bhodRSgbIeA8pk8-99kY0_if2jVlk3xra4KY0ytbKS4/edit?usp=sharing

![Screen Shot 2021-06-09 at 14 15 19](https://user-images.githubusercontent.com/44729662/121297343-223bfc80-c92d-11eb-948f-fdeedbbb2d64.png)

**Comment by Aki-7** [comment]
I changed the OGP image with the 1280x640 image with 80 px padding, which is recommended by GitHub.

If there is no negative feedback, I'll close this issue.
