### ISSUE TITLE
Consider converting the repo to a multi-module Maven project?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remoting-opentelemetry-plugin#15]
At the meetings we discussed having a multi-module maven repo so that the Library could be developed in a separate and potentially detachable component. Not sure it is still planned but just in case

**Comment by Aki-7** [comment]
I didn't think it is needed, but #21 changed my mind.
I will split the monitoring engine module and Jenkins plugin module.
Are there any instructions to do that in Jenkins infrastructure?
