### ISSUE TITLE
Defining definition of done in pull request templates

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remoting-opentelemetry-plugin#16]
Follow-up to the conversation in Slack.

Maybe we need to separately agree on a definition of done for a pull request / issue. In Jenkins we usually follow the Continuous Integration approach, and we try to keep every issue and pull request an independent deliverable. What it means that we usually try to have an atomic change which can be delivered separately.

E.g. issues could include the following default checklist:

- [ ] Change is code complete, no regressions
- [ ] All follow-ups are documented as issues and-or TODO comments
- [ ] There is decent test coverage for the issue
- [ ] If needed, there is user documentation added
- [ ] If needed, there is developer documentation added
- [ ] If needed, there is a component release performed

Something like that. You could think a bit about your definition of done and maybe create an issue template for it. For example, here are our default GitHub pull request and issue templates in Jenkins:

* https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md
* https://github.com/jenkinsci/.github/tree/master/.github/ISSUE_TEMPLATE

They are not the best one for particular project, please feel free to override

**Comment by Aki-7** [comment]
I think the PR template should have a strict checklist to keep the PR an independent deliverable, but issues can be more flexible, I think.
