### ISSUE TITLE
Conduct user survey of Jenkins Remoting monitoring needs

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remoting-opentelemetry-plugin#18]
As agreed in the chat, we want to to conduct a user survey to understand the key pain points of users

// TODO: Add details from Slack

**Comment by oleg-nenashev** [comment]
Hi @Aki-7. Could you please add details and action plan based on the Slack conversations?

**Comment by Aki-7** [comment]
The survey aims to understand the key pain points of users about agent management and we use them to find out what kind of trace or metrics are needed.

The draft survey forms are here

- https://forms.gle/8b6q78oQNnYPK9667 (@Aki-7  creates)
- https://forms.gle/LPiJttgaH1kr2nm59 (@oleg-nenashev enhances former one)
I added +1 for the latter one.

The planning publishment ways are

- sending this form to Jenkins Mailing lists
  - jenkinsci-dev@googlegroups.com
  - jenkinsci-gsoc-all-public@googlegroups.com 
- sending this form to colleagues if possible

I'll conduct the plan tomorrow if there is no negative feedback!

**Comment by oleg-nenashev** [comment]
Fine with me. I will also help to promote. Maybe q project intro blogpost
with a survey as well?

**Comment by Aki-7** [comment]
Do you mean the blogpost of https://jenkins.io/node? That's a great idea!

**Comment by oleg-nenashev** [comment]
Yep

**Comment by Aki-7** [comment]
I send it to the dev list and waiting for the approval.
