### ISSUE TITLE
[Discussion] The critical problem of phase1 design

### ISSUE THREAD

**Issue by Aki-7** [jenkinsci/remoting-opentelemetry-plugin#21]
I found the critical problem of the current design for phase1

[mini design doc](https://docs.google.com/document/d/1PpS9Bmz7K11iigPQoqI-5qJo4km0vsmcI1VYIaOo8mU/edit?usp=sharing)

In phase1, the controller will send a monitoring engine to each agent and the monitoring engine will keep running even if the connection between controller and agent is lost.
However, according to the remoting implementation, we cannot load new classes from RemotingClassLoader without an open channel.
So we will encounter NoClassDefFoundError when the monitoring engine does something new while the channel is offline.

[Relevant code]( https://github.com/jenkinsci/remoting/blob/15021cbc7a650b0b69060fb42da55b8d2d39e9cb/src/main/java/hudson/remoting/RemoteClassLoader.java#L199-L228)

Possible solutions I come up with are

- We will not run the monitoring engine while the channel is offline.
or
- Load class from somewhere other than RemotingClassLoader.

I like the latter one because the solution leads to the phase2 achievement, and we can use the `-cp` option of `agent.jar`.

So in the phase1,
- Enable Monitoring engine to be loaded from system classloader
- Controller sends the simple monitoring engine launcher to agents

And in the phase2
- Enable to download something like `monitoring-engine.jar` from plugin endpoint. 
- Enable to configure the engine without controller
- Enable to launch the engine without controller

I'll update design doc.

close this issue after updated the design doc.

**Comment by oleg-nenashev** [comment]
It is also possible to pre-load all classes on the agent side.

FTR by default Jenkins agents have a local JAR cache. Even if there is "Remote Classloading" per se, in fact the whole JAR is being propagated over the channel and cached on the remote side. Then the Remoting classloader just loads classes from these JARs when possible without remote loading. So probably the critical problem is not THAT critical

**Comment by Aki-7** [comment]
> It is also possible to pre-load all classes on the agent side.
That's good news!!!

I'll look into it!
