### ISSUE TITLE
Announce the project in the jenkins.io blog

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/remoting-opentelemetry-plugin#25]
It would be nice to announce the project on jenkins.io as a blog and to link a survey there.

* HOWTO: https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-a-blog-post

**Comment by Aki-7** [comment]
https://www.jenkins.io/blog/2021/07/31/remoting-monitoring-phase-1/

I should have posted another blog including the survey before this.
