### ISSUE TITLE
UnixSlaveRestarter kill all the threads.

### ISSUE THREAD

**Issue by Aki-7** [jenkinsci/remoting-opentelemetry-plugin#65]
# Description

The monitoring engine is a thread, and I expect the thread to keep running over reconnection to collect telemetry data continuously.

However in unix agents, `UnixSlaveRestarter` restarts the agent with `execv`. So all the thread will be killed of course.
So it seems impossible to keep monitoring engine running by using thread.
I didn't realize the existence of the restarter till now since the restarter doesn't work when I start the Jenkins controller with
```
mvn hpi:run
``` 

I intended to check the production environment by uploading hpi file to the normal Jenkins controller, but I missed something...

But if we are able to launch the monitoring engine when the `agent.jar` executed, we don't need to handle this problem so I'll forcuse on how to launch the monitoring engine with the `agent.jar`.

**Comment by oleg-nenashev** [comment]
It might make sense to add an exception for the monitoring threads. It might require some patches on the Jenkins core side though

**Comment by Aki-7** [comment]
As the restarter seems to restart the process itself, adding an exception for a thread seems impossible.

It's viable to create a fork before `execv` and kill all the threads of the parent process other than monitoring threads.
But it seems to make the system more unreliable...

I'm planning to launch the monitoring engine together with the `hudson.Luancher` in the future (during GSoC).
And then, It's ok to restart the process by `execv` because the monitoring will restart soon and can keep collecting the telemetry data.

So how about focusing on starting the monitoring engine together with the `hudson.Luancher`, and removing the functionality to send and install the monitoring engine from the Jenkins controller in the near future?

ref: 
https://github.com/jenkinsci/jenkins/blob/95e85495ca6b26ba61ff4a1bf18d181d5e218bc9/core/src/main/java/jenkins/slaves/restarter/UnixSlaveRestarter.java#L50-L63
```java
    public void restart() throws Exception {
        // close all files upon exec, except stdin, stdout, and stderr
        int sz = LIBC.getdtablesize();
        for (int i = 3; i < sz; i++) {
            int flags = LIBC.fcntl(i, F_GETFD);
            if (flags < 0) continue;
            LIBC.fcntl(i, F_SETFD, flags | FD_CLOEXEC);
        }


        // exec to self
        String exe = Daemon.getCurrentExecutable();
        LIBC.execv(exe, new StringArray(args.toArray(new String[0])));
        throw new IOException("Failed to exec '" + exe + "' " + LIBC.strerror(Native.getLastError()));
    }
```

**Comment by oleg-nenashev** [comment]
> So how about focusing on starting the monitoring engine together with the hudson.Luancher, and removing the functionality to send and install the monitoring engine from the Jenkins controller in the near future?

Might be feasible since it is an end goal anyway

**Comment by jglick** [comment]
> I'm planning to launch the monitoring engine together with the `hudson.Luancher` in the future (during GSoC).

That is https://github.com/jenkinsci/remoting/pull/471 IIUC?

> And then, It's ok to restart the process by `execv` because the monitoring will restart soon and can keep collecting the telemetry data.

How is this any different? If you inject the monitoring engine from a plugin when a connection is established, that should happen again after a restart.

**Comment by jglick** [comment]
BTW I am tempted to just delete the whole `jenkins.slaves.restarter` package, or at least move it to a plugin you can install if you really think you need this behavior _and_ are willing to put up with the use of Akuma/JNA or `winsw` on Unix or Windows (respectively). AFAIK its sole purpose is to make sure that a new JVM is used for each reconnection attempt by an inbound agent. ([JENKINS-19055](https://issues.jenkins.io/browse/JENKINS-19055)) But that is something that would be better handled by a service wrapper: if the agent disconnects, it should simply exit, and let a wrapper process launch a new process normally (no low-level `execv` trickery). The restart-in-place logic really only makes sense for an obsolete universe in which people launch agents by clicking on a JNLP launch button in a web browser running from a Windows computer somewhere. See also https://github.com/jenkinsci/jep/blob/master/jep/230/README.adoc#marking-slave-installer-as-detached

**Comment by Aki-7** [comment]
>> I'm planning to launch the monitoring engine together with the hudson.Luancher in the future (during GSoC).
>
>That is jenkinsci/remoting#471 IIUC?

yes!

>> And then, It's ok to restart the process by execv because the monitoring will restart soon and can keep collecting the telemetry data.
>
> How is this any different? If you inject the monitoring engine from a plugin when a connection is established, that should happen again after a restart.

I want to collect data after the agent restarts before the new connection is established.
I can't say the data is important with some concrete evidence, but it seems important to get the metrics right after the sporadic disconnection happens and before the connection get back to normal.

And if the agent tries to connect the controller several times before the new connection is established, I want to know why they failed. Did it fail to fetch the JNLP file (just a simple HTTP request) or fail to establish the channel? I think a temporary disorder of a network component may bring this kind of situation.

It's difficult to point out what kind of monitoring is valuable even though I'm trying to figure it out, but your opinion helps me to clarify it. Thank you so much!

**Comment by jglick** [comment]
> after the agent restarts before the new connection is established

So this would data from the new JVM while the agent is trying to make a TCP or WebSocket connection, going through Remoting handshake, and doing some initial class loading, that sort of thing? I can see how this _might_ be important in some circumstances, when there are long delays or total failures establishing connections. I am just not sure whether it is important enough to justify making system setup and configuration more complex and manual. Connection problems typically have a specific cause that is apparent once you look at agent logs. (E.g. in Kubernetes clusters, you can run `kail` to get logs from every pod, even if it shuts down almost immediately and goes into a crash backoff loop.) Most of the difficult problems I have heard of people having with Remoting—the ones that we are not consistently able to diagnose and solve—involve the agent abruptly disconnecting with no clear log message after it had been running for a while.

CC @jeffret-b. The conversation got split a bit here.

**Comment by jeffret-b** [comment]
I agree that I don't like making setup and configuration more complex in normal cases to support gathering data during the initial connection phases. I can't really think of any instances I've ever heard of where having that information would provide significant help. Most initial connection issues I've ever seen involve issues in network routing. It's not able to make the socket connection for a variety of reasons. There is little that can be gained from Remoting traces in these instances. With these it's either connecting or its not.

The difficult issues people report with Remoting involve (seemingly) random disconnects after it has been running. These have a variety of causes, but it's extremely rare that it's anything to do directly with Remoting or that can be monitored from inside Remoting. These are more difficult to isolate because they appear infrequently and randomly.

Making setup and config more difficult will create more issues than it solves in this area.

**Comment by jeffret-b** [comment]
> BTW I am tempted to just delete the whole `jenkins.slaves.restarter` package, or at least move it to a plugin you can install if you really think you need this behavior _and_ are willing to put up with the use of Akuma/JNA or `winsw` on Unix or Windows (respectively). AFAIK its sole purpose is to make sure that a new JVM is used for each reconnection attempt by an inbound agent. ([JENKINS-19055](https://issues.jenkins.io/browse/JENKINS-19055)) But that is something that would be better handled by a service wrapper: if the agent disconnects, it should simply exit, and let a wrapper process launch a new process normally (no low-level `execv` trickery). The restart-in-place logic really only makes sense for an obsolete universe in which people launch agents by clicking on a JNLP launch button in a web browser running from a Windows computer somewhere.

I agree with and support all of this. 

While I haven't been able to remove WebStart support from Jenkins yet, WebStart support is essentially useless. It's possible to get it to work, but it's complicated and only gets increasingly so.

Jenkins shouldn't implement any of its own special restarters. These should be modular, standard existing components as much as possible. The existing Windows "Install as Service" is problematic, doesn't work for various configurations, and is difficult to enhance.

**Comment by Aki-7** [comment]
Thank you so much for your valuable opinions! I also agree with you and my project needs to pivot a little.

Thank you so much again!
